name=input("Enter your name: ")
age=int(input("Enter your age: "))
income=float(input("Enter your income: "))
print("The information you input are")
print("Name: ", name)
print("age: " ,age)
print("income: ",format(income,'12,.2f'))